// <auto-generated />
// ВНИМАНИЕ: файл АВТОГЕНЕРИРОВАН командой `dotnet ef migrations add InitialCreate` и вручную не правится.
// Это вторая (служебная) половина класса InitialCreate: хранит «слепок» модели на момент миграции. Комментарии добавлены только для защиты.
// Пространство имён System: DateTime.
using System;
// Пространство имён Lab6.Data: тип NoteContext для атрибута [DbContext].
using Lab6.Data;
// Пространство имён EF Core: ModelBuilder, DeleteBehavior.
using Microsoft.EntityFrameworkCore;
// Инфраструктура EF Core: атрибут [DbContext].
using Microsoft.EntityFrameworkCore.Infrastructure;
// Пространство имён миграций: атрибут [Migration].
using Microsoft.EntityFrameworkCore.Migrations;
// Пространство имён конвертации значений (подключено генератором).
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

// Отключаем проверку nullable для сгенерированного кода.
#nullable disable

// Пространство имён миграций проекта.
namespace Lab6.Migrations
{
    // Атрибут: эта миграция относится к контексту NoteContext.
    [DbContext(typeof(NoteContext))]
    // Атрибут: идентификатор миграции (метка времени + имя); именно он записывается в таблицу __EFMigrationsHistory после применения.
    [Migration("20260922222139_InitialCreate")]
    // Вторая часть partial-класса InitialCreate (первая - в InitialCreate.cs с методами Up/Down).
    partial class InitialCreate
    {
        /// <inheritdoc />
        // Описывает модель данных «как она была» на момент этой миграции; EF сравнивает её со снимком, чтобы вычислять следующие миграции.
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
// Подавляем предупреждения об устаревших API в сгенерированном коде.
#pragma warning disable 612, 618
            // Версия EF Core, создавшая миграцию.
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            // Сущность связи many-to-many "CategoryNote" (промежуточная таблица, создана автоматически из связи Note-Category).
            modelBuilder.Entity("CategoryNote", b =>
                {
                    // Столбец CategoriesId: целое.
                    b.Property<int>("CategoriesId")
                        .HasColumnType("INTEGER");

                    // Столбец NotesId: целое.
                    b.Property<int>("NotesId")
                        .HasColumnType("INTEGER");

                    // Составной первичный ключ.
                    b.HasKey("CategoriesId", "NotesId");

                    // Индекс по NotesId.
                    b.HasIndex("NotesId");

                    // Физическое имя таблицы: NoteCategory (из Fluent API в NoteContext).
                    b.ToTable("NoteCategory", (string)null);
                });

            // Сущность Lab6.Models.Category.
            modelBuilder.Entity("Lab6.Models.Category", b =>
                {
                    // Id: автогенерируется при добавлении.
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    // Description: обязательное (из [Required]).
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    // Title: обязательное, максимум 100 символов (из [Required] и [StringLength(100)]).
                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    // Первичный ключ Id.
                    b.HasKey("Id");

                    // Имя таблицы Categories.
                    b.ToTable("Categories");
                });

            // Сущность Lab6.Models.Note.
            modelBuilder.Entity("Lab6.Models.Note", b =>
                {
                    // Id: автогенерируется.
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    // Date: дата заметки (в SQLite - TEXT).
                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    // Description: обязательное.
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    // Title: обязательное, максимум 200 символов.
                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    // Первичный ключ Id.
                    b.HasKey("Id");

                    // Имя таблицы Notes.
                    b.ToTable("Notes");
                });

            // Внешние ключи таблицы связи.
            modelBuilder.Entity("CategoryNote", b =>
                {
                    // Связь с Category: CategoriesId -> Categories.Id; удаление категории каскадно удаляет строки связи.
                    b.HasOne("Lab6.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    // Связь с Note: NotesId -> Notes.Id; удаление заметки каскадно удаляет строки связи.
                    b.HasOne("Lab6.Models.Note", null)
                        .WithMany()
                        .HasForeignKey("NotesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
// Возвращаем предупреждения в обычный режим.
#pragma warning restore 612, 618
        } // конец BuildTargetModel
    } // конец класса InitialCreate
} // конец пространства имён Lab6.Migrations
