// <auto-generated />
// ВНИМАНИЕ: файл АВТОГЕНЕРИРОВАН командой `dotnet ef migrations add ...` (обновляется при каждой новой миграции) и вручную не правится.
// Снимок ТЕКУЩЕЙ модели: EF сравнивает его с классами Note/Category/NoteContext и по разнице строит новую миграцию. Комментарии добавлены только для защиты.
// Пространство имён System: DateTime.
using System;
// Пространство имён Lab6.Data: NoteContext для атрибута [DbContext].
using Lab6.Data;
// Пространство имён EF Core: ModelBuilder, DeleteBehavior.
using Microsoft.EntityFrameworkCore;
// Инфраструктура EF Core: атрибут [DbContext], ModelSnapshot.
using Microsoft.EntityFrameworkCore.Infrastructure;
// Пространство имён конвертации значений (подключено генератором).
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

// Отключаем проверку nullable для сгенерированного кода.
#nullable disable

// Пространство имён миграций проекта.
namespace Lab6.Migrations
{
    // Атрибут: снимок относится к контексту NoteContext.
    [DbContext(typeof(NoteContext))]
    // Класс снимка. Его находит сам EF Core при выполнении Migrate() и при `dotnet ef migrations add`.
    partial class NoteContextModelSnapshot : ModelSnapshot
    {
        // Описание модели «как есть сейчас» (то же, что в BuildTargetModel последней миграции).
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
// Подавляем предупреждения об устаревших API в сгенерированном коде.
#pragma warning disable 612, 618
            // Версия EF Core.
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            // Сущность связи many-to-many (таблица NoteCategory).
            modelBuilder.Entity("CategoryNote", b =>
                {
                    // Столбец CategoriesId.
                    b.Property<int>("CategoriesId")
                        .HasColumnType("INTEGER");

                    // Столбец NotesId.
                    b.Property<int>("NotesId")
                        .HasColumnType("INTEGER");

                    // Составной первичный ключ из двух столбцов.
                    b.HasKey("CategoriesId", "NotesId");

                    // Индекс по NotesId.
                    b.HasIndex("NotesId");

                    // Имя таблицы: NoteCategory.
                    b.ToTable("NoteCategory", (string)null);
                });

            // Сущность Category (таблица Categories).
            modelBuilder.Entity("Lab6.Models.Category", b =>
                {
                    // Id: автогенерируемый первичный ключ.
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    // Description: обязательное (из [Required]).
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    // Title: обязательное, до 100 символов.
                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    // Первичный ключ.
                    b.HasKey("Id");

                    // Таблица Categories.
                    b.ToTable("Categories");
                });

            // Сущность Note (таблица Notes).
            modelBuilder.Entity("Lab6.Models.Note", b =>
                {
                    // Id: автогенерируемый первичный ключ.
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    // Date: дата заметки.
                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    // Description: обязательное.
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    // Title: обязательное, до 200 символов.
                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    // Первичный ключ.
                    b.HasKey("Id");

                    // Таблица Notes.
                    b.ToTable("Notes");
                });

            // Внешние ключи таблицы связи.
            modelBuilder.Entity("CategoryNote", b =>
                {
                    // Внешний ключ CategoriesId -> Categories.Id, каскадное удаление.
                    b.HasOne("Lab6.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    // Внешний ключ NotesId -> Notes.Id, каскадное удаление.
                    b.HasOne("Lab6.Models.Note", null)
                        .WithMany()
                        .HasForeignKey("NotesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
// Возвращаем предупреждения в обычный режим.
#pragma warning restore 612, 618
        } // конец BuildModel
    } // конец класса NoteContextModelSnapshot
} // конец пространства имён Lab6.Migrations
